### ISSUE TITLE
Array is a built-in name in Julia Base

### ISSUE THREAD

**Issue by rayegun** [youwuyou/Ginkgo.jl#17]
Hi! Excited to see Gingko coming to Julia! One immediate issue is that the type `Base.Array` already exists in Julia. Having a type `Gingko.Array` is quite problematic, especially since it is exported. You will see an error like:

```julia
julia> Array
WARNING: both Ginkgo and Base export "Array"; uses of it in module Main must be qualified
ERROR: UndefVarError: `Array` not defined
```

This will cause issues for every person who loads Gingko.jl. I would strongly recommend renaming this to `GingkoArray` or something similar.

**Comment by pratikvn** [comment]
+1 for `GkoArray`. Probably makes sense to have `Gko` prefixes everywhere for Ginkgo types. Julia convention seems to be to [use camel case for all types](https://docs.julialang.org/en/v1/manual/style-guide/#Use-naming-conventions-consistent-with-Julia-base/), which is different from Ginkgo's convention.

**Comment by youwuyou** [comment]
Nice I will go for `GkoArray` then and will stick to the Julia convention. 

@pratikvn Regarding always having the prefix `Gko`, I was just thinking maybe for types like `Ginkgo.Dense`  which does not conflict with [`Base.DenseMatrix`](https://docs.julialang.org/en/v1/base/arrays/#Base.DenseMatrix) we don't necessarily need to use `GkoDense` as the name?

**Comment by pratikvn** [comment]
`Base` might not have a conflict, but in case some other package has a `Dense` type, which is likely, and a user loads that package and Ginkgo, then they will have a conflict.
